version: "3.8"

services:
  hr-worker-pg12:
    image: postgres:12-alpine
    container_name: hr-worker-pg12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: db_hr_worker
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}

networks:
  default:
    name: hr-net
