server:
  port: ${PORT:0}

spring:
    application:
        name: hr-payroll

resilience4j:
    timelimiter:
        configs:
            default:
                timeout-duration: 10s
        
eureka:
    client:
        fetchRegistry: true
        service-url:
            defaultZone: http://hr-eureka-server:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.aplication.instance_id:${random.value}}
        preferIpAddress: true