server:
  port: 8101

spring:
    application:
        name: hr-payroll

resilience4j:
    timelimiter:
        configs:
            default:
                timeout-duration: 10s
        
eureka:
    client:
        fetchRegistry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true