server:
  port: 8101

spring:
    application:
        name: hr-payroll
    cloud:
        loadbalancer:
            ribbon:
                enable: true

hr-worker:
    ribbon:
        listOfServers: localhost:8001, localhost:8002