server:
  port: ${PORT:0}

eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.aplication.instance_id:${random.value}}
        preferIpAddress: true
    client:
        service-url:
            defaultZone: http://hr-eureka-server:8761/eureka/

spring:
    config:
        import: "optional:configserver:"
    profiles:
        active: prod
    application:
        name: hr-worker
    jpa:
        defer-datasource-initialization: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
