server:
  port: ${PORT:0}

eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.aplication.instance_id:${random.value}}
        preferIpAddress: true
    client:
        fetchRegistry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name: hr-oauth
    config:
        import: "optional:configserver:"
