server:
  port: ${PORT:0}

eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.aplication.instance_id:${random.value}}
        preferIpAddress: true
    client:
        fetchRegistry: true
        service-url:
            defaultZone: http://hr-eureka-server:8761/eureka/

spring:
    application:
        name: hr-oauth
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://hr-config-server:8888

management:
    endpoints:
        web:
            exposure:
                include: "*"