spring:
    application:
        name: hr-api-gateway-zuul
    main:
        web-application-type: reactive
    cloud:
        gateway:
            routes:
                - id: hr-worker
                  uri: lb://hr-worker
                  predicates:
                    - Path=/hr-worker/**
                  filters:
                    - RewritePath=/hr-worker/(?<segment>.*), /$\{segment}
                - id: hr-payroll
                  uri: lb://hr-payroll
                  predicates:
                    - Path=/hr-payroll/**
                  filters:
                    - RewritePath=/hr-payroll/, /

server:
    port: 8765
        
eureka:
    client:
        fetchRegistry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true