spring:
    application:
        name: hr-api-gateway-zuul
    main:
        web-application-type: reactive
        allow-bean-definition-overriding: true
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://hr-config-server:8888
        gateway:
            routes:
                - id: hr-worker
                  uri: lb://hr-worker
                  predicates:
                    - Path=/hr-worker/**
                  filters:
                    - RewritePath=/hr-worker/(?<segment>.*), /$\{segment}
                - id: hr-payroll
                  uri: lb://hr-payroll
                  predicates:
                    - Path=/hr-payroll/**
                  filters:
                    - RewritePath=/hr-payroll/, /
                - id: hr-user
                  uri: lb://hr-user
                  predicates:
                    - Path=/hr-user/**
                  filters:
                    - RewritePath=/hr-user/, /
                - id: hr-oauth
                  uri: lb://hr-oauth
                  predicates:
                    - Path=/hr-oauth/**
                  filters:
                    - RewritePath=/hr-oauth/, /

server:
    port: 8765
        
eureka:
    client:
        fetchRegistry: true
        service-url:
            defaultZone: http://hr-eureka-server:8761/eureka/
    instance:
        preferIpAddress: true

management:
    endpoints:
        web:
            exposure:
                include: "*"